### ISSUE TITLE
Circle CI keeps failing

### ISSUE THREAD

**Issue by johnsekar** [KarrLab/wc_rules#12]
Latest build:
https://app.circleci.com/pipelines/github/KarrLab/wc_rules/183/workflows/0ea59c1b-e5f2-4d40-8706-c76a7e36c528/jobs/1233

**Comment by jonrkarr** [comment]
This is an issue with `setup.py` (installation script for `wc_rules`). The issue isn't specific to CircleCI. You can execute the setup script locally be running `pip install -e .` from the root directory for `wc_rules`.

The issue is that the `git+https://github.com/KarrLab/obj_tables.git#egg=obj_tables` should be replaced with `objtables` in 
`requirements.txt`.

**Comment by johnsekar** [comment]
> The issue is that the git+https://github.com/KarrLab/obj_tables.git#egg=obj_tables should be replaced with objtables in
requirements.txt.

Using just obj_tables in requirements.txt uses the release version of obj_tables, which does not specify version requirements on biopython. This breaks with biopython 1.78, so I just committed a patch to obj_tables to fix that.

**Comment by jonrkarr** [comment]
You can also use `git+https://github.com/KarrLab/obj_tables.git#egg=obj_tables == x.y.z.`

**Comment by jonrkarr** [comment]
If you need a specific branch, you can use  `git+https://github.com/KarrLab/obj_tables.git@branch#egg=obj_tables == x.y.z`
